singleWordLanguages = [
    'Afrikaans',
    'Albanian',
    'Anatolian',
    'Anglo-Norman', 
    'Aragonese', 
    'Asturian', 
    'Avestan', 
    'Belarusian', 
    'Bokmål', 
    'Breton', 
    'Brittonic', 
    'Bulgarian', 
    'Catalan', 
    'Cornish', 
    'Corsican', 
    'Czech', 
    'Dalmatian', 
    'Danish', 
    'Dutch', 
    'English', 
    'Faroese', 
    'Finnic', 
    'Frankish', 
    'French', 
    'Galician', 
    'German', 
    'Gothic', 
    'Greek', 
    'Hittite', 
    'Icelandic', 
    'Irish', 
    'Italian', 
    'Ladin', 
    'Latin', 
    'Latvian', 
    'Lithuanian', 
    'Luwian', 
    'Luxembourgish', 
    'Norman', 
    'Norn', 
    'Norwegian', 
    'Nynorsk', 
    'Occitan', 
    'Plautdietsch', 
    'Polish', 
    'Portuguese', 
    'Proto-Baltic', 
    'Proto-Celtic', 
    'Proto-Germanic', 
    'Proto-Greek', 
    'Proto-Indo-European', 
    'Proto-Italic', 
    'Proto-Slavic', 
    'Romanian', 
    'Romansch', 
    'Russian', 
    'Samic', 
    'Sanskrit', 
    'Sardinian', 
    'Scots', 
    'Serbo-Croatian', 
    'Sicilian', 
    'Slovak', 
    'Slovakian', 
    'Slovene', 
    'Spanish', 
    'Swedish', 
    'Ukrainian', 
    'Walloon',
    'Welsh',
    'Yiddish',
    ]

twoWordLanguages = [
    'Ancient Greek',
    'Low German',
    'Medieval Latin', 
    'Middle Dutch', 
    'Middle English', 
    'Middle French', 
    'Middle Irish', 
    'North Frisian', 
    'Norwegian Bokmål', 
    'Norwegian Nynorsk', 
    'Old Dutch', 
    'Old English', 
    'Old French', 
    'Old Frisian', 
    'Old Norse', 
    'Old Occitan', 
    'Old Polish', 
    'Old Portuguese', 
    'Old Saxon', 
    'Old Swedish', 
    'Proto-West Germanic', 
    'Saterland Frisian', 
    'Scottish Gaelic', 
    'Tocharian A', 
    'Tocharian B', 
    'Vulgar Latin', 
    'West Frisian', 
    'West Germanic', 
    ]

threeWordLanguages = [
    'Middle High German',
    'Middle Low German',
    'Old Church Slavonic',
    'Old High German',
    ]

